update BluetoothStack.wprp with additional providers
microsoft/busiotools pull request #109
Opened 2022-08-04 17:41 UTC by SamPavezaMS

2022-08-04 17:54 UTC, erikpe-msft commented on bluetooth/tracing/BluetoothStack.wprp
> +    <EventProvider Id="ApxGuid.Verbose" Name="96760AC7-C416-43A7-AA7F-1A676942589C" Level="4" NonPagedMemory="false">
>4 [](http://example.com/codeflow?start=91&length=1)

This should probably be "5" and "ApxGuid" should be "4"

2022-08-04 17:55 UTC, erikpe-msft commented on bluetooth/tracing/BluetoothStack.wprp
> +    <EventProvider Id="AcxLogger" Name="2393C85D-B36A-4FE2-86A9-12500A05B76A" Level="5" NonPagedMemory="true">
>5 [](http://example.com/codeflow?start=85&length=1)

Intentionally "5" in non-Verbose?

2022-08-04 17:56 UTC, erikpe-msft commented on bluetooth/tracing/BluetoothStack.wprp
> +    <EventProvider Id="ApxKm.Verbose" Name="E3A25276-CD6E-40DC-8BB6-1659A5E00952" Level="4" NonPagedMemory="true">
>"4" [](http://example.com/codeflow?start=88&length=3)

Swap level with "ApxKm"?

2022-08-04 17:57 UTC, erikpe-msft commented on bluetooth/tracing/BluetoothStack.wprp
> -            <EventProviderId Value="Microsoft.Windows.TestExecution.WexLogger"/>
><EventProviderId Value="Microsoft.Windows.TestExecution.WexLogger"/> [](http://example.com/codeflow?start=12&length=68)

Please add this back

2022-08-04 17:57 UTC, erikpe-msft commented on bluetooth/tracing/BluetoothStack.wprp
> -            <EventProviderId Value="Microsoft.Windows.TestExecution.WexLogger"/>
><EventProviderId Value="Microsoft.Windows.TestExecution.WexLogger"/> [](http://example.com/codeflow?start=12&length=68)

Please add this back

2022-08-04 17:58 UTC, erikpe-msft commented on bluetooth/tracing/BluetoothStack.wprp
> +            <EventProviderId Value="ApxKm"/>
>ApxKm [](http://example.com/codeflow?start=36&length=5)

.Verbose?

2022-08-04 17:58 UTC, erikpe-msft commented on bluetooth/tracing/BluetoothStack.wprp
> +            <EventProviderId Value="AcxLogger"/>
>AcxLogger [](http://example.com/codeflow?start=36&length=9)

.Verbose?

2022-08-04 17:59 UTC, erikpe-msft requested changes
:clock1:

2022-08-04 18:04 UTC, erikpe-msft commented
In general, how would you describe the verbosity of these new providers, when compared with providers that we already have? We do have to be sensitive to significantly increasing the size of our trace files, especially if it can impact "all" Bluetooth trace scenarios.

2022-08-04 20:17 UTC, SamPavezaMS commented
> In general, how would you describe the verbosity of these new providers, when compared with providers that we already have? We do have to be sensitive to significantly increasing the size of our trace files, especially if it can impact "all" Bluetooth trace scenarios.

@Erik not sure how to contextualize this, maybe we should meet offline. After pairing I see 71 apx traces and 23K acx traces.

2022-08-05 00:19 UTC, erikpe-msft commented on bluetooth/tracing/BluetoothStack.wprp
> +		<EventProviderId Value="Microsoft.Windows.TestExecution.WexLogger"/>
>		 [](http://example.com/codeflow?start=0&length=2)

two wild tabs appear :)

2022-08-05 00:21 UTC, erikpe-msft commented on bluetooth/tracing/BluetoothStack.wprp
> +		<EventProviderId Value="Microsoft.Windows.TestExecution.WexLogger"/>
>		 [](http://example.com/codeflow?start=0&length=2)

oh no, more wild tabs!

2022-08-05 00:29 UTC, erikpe-msft approved these changes
:shipit:

2022-08-05 16:30 UTC, SamPavezaMS commented on bluetooth/tracing/BluetoothStack.wprp
> +		<EventProviderId Value="Microsoft.Windows.TestExecution.WexLogger"/>
added back

2022-08-05 22:50 UTC, merged